# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_events', '0023_auto_20160212_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalendarplugin',
            name='cache_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached."),
        ),
        migrations.AddField(
            model_name='upcomingpluginitem',
            name='cache_duration',
            field=models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached."),
        ),
        migrations.AlterField(
            model_name='registration',
            name='language_code',
            field=models.CharField(choices=[('en', 'en'), ('de', 'de')], default='en', max_length=32),
        ),
    ]
