# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_events', '0025_auto_20160802_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsconfig',
            name='namespace',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace'),
        ),
        migrations.AlterField(
            model_name='eventsconfig',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='language_code',
            field=models.CharField(choices=settings.LANGUAGES, default='en', max_length=32),
        ),
        migrations.AlterField(
            model_name='upcomingpluginitem',
            name='latest_entries',
            field=models.PositiveSmallIntegerField(default=5, help_text='The number of latest events to be displayed.', verbose_name='latest entries'),
        ),
    ]
